---
title: "Blog Post 1: The Use of the Offset"
subtitle: "DT 621---Fall 2020"
author: "Avraham Adler"
date: "9/13/2020"
output: html_document
bibliography: 'D:\\Users\\Parents\\Documents\\SpiderOak\\LaTeX\\LaTeX\\BibTeX\\AviRefsBiblatex.bib'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
In my area of expertise, non-life reinsurance, there is not that much call for
linear regression. However, in primary insurance, generalized linear models
(GLM) are used very often to set rates and class plans. A common example is in
personal auto insurance, where there is a lot of driver data, and models are fit
to features such as marital status, sex, age, and location. 

Focusing on auto physical damage, the loss an insurer pays for first party
property damage to the car (when the driver hits another car), the expected
losses are a function of both frequency and severity. Severity is a function of
the value of car being driven. Frequency, however, depends on the driver. Often,
a GLM is used to estimate frequency.

As accidents, at least at first glance, can be considered a Poisson process, a
GLM with a Poisson link function is very common. As frequency of events is
clearly a function of the number of drivers, the models are often constructed to
measure the rate of accident per unit of exposure, where the exposure could be
drivers, cars, miles driven, or car-years insured. It is in this context I first
came across offsets in 
@Yan.etal-2009-ApplicationsOfTheOffsetInPropertyCasualtyPredictiveModeling. The
authors describe using an offset in a Poisson model to measure the rate instead
of the amount.

In OLS, which were are studying, the use of the offset term is less common, for
one can simply subtract the offset from the observations and proceed. But in
non-additive models,---the Poisson is multiplicative---it has a larger role.
Thus, I decided to take this opportunity compare running a Poisson model with
and without an offset and compare them.

# Create Synthetic Data
## True Regression Model
Let's create data where the frequency of accidents is a Poisson process with the
following rates per unit of exposure:

|Variable|Value|
|--------|-----|
|Grand Mean|0.01|
|Male|.10|
|Married| -0.08|
|Region: NE|0.05|
|Region: S|0.1|
|Region: NC (North Central)|0|
|Region: W| -0.03|

So the 

Let's generate 5 years worth of exposures as a Poisson random variable with mean
of 100, and calculate


# References